# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Lint
run-name: "Lint \"${{ github.event.pull_request.title || github.event.head_commit.message }}\" by @${{ github.actor }}"
on:
  push: { branches: [master], paths-ignore: ["**/*.md", "LICENSE"] }
  pull_request: { branches: [master], paths-ignore: ["**/*.md", "LICENSE"] }
permissions: { contents: read }
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with: { persist-credentials: false }
      - uses: kjanat/runner@master
      - { uses: ./.github/actions/setup-node-bun, with: { install: "true", frozen-lockfile: "true" } }
      - run: run -s typecheck lint fmt:check:list build
      - uses: actions/upload-artifact@v7
        with: { name: index-html, path: index.html, if-no-files-found: error, retention-days: 2 }
