name: Lint
run-name: "Lint \"${{ github.event.pull_request.title || github.event.head_commit.message }}\" by @${{ github.actor }}"
on:
  push: { branches: [master], paths-ignore: ["**/*.md", "LICENSE"] }
  pull_request: { branches: [master], paths-ignore: ["**/*.md", "LICENSE"] }
permissions: { contents: read }
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with: { persist-credentials: false }
      - { uses: ./.github/actions/setup-node-bun, with: { install: "true", frozen-lockfile: "true" } }
      - run: bun typecheck
      - run: bun lint
      - run: bun fmt:check --list-different
      - run: bun run build
      - name: Upload built index.html
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: index-html
          path: index.html
          if-no-files-found: error
          retention-days: 2
